name: Node.js Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'npm'
    - run: npm install --production=false
    - run: npm run build --if-present
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{secrets.ACTIONS_DEPLOY_KEY}}
        publish_dir: ./dist
        
    
